/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    [key: string]: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    '/dev_interior.gltf'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.574, 0.806, -0.295]}
        rotation={[0, 1.452, 0]}
        scale={0.067}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064.geometry}
          material={materials['computer black.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064_1.geometry}
          material={materials['5 Light lamp blueLIGHT.001']}
        />
      </group>
      <group
        position={[0.046, 1.139, -1.727]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.181, 0.486, 0.346]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials['Material.032']}
        />
      </group>
      <group
        position={[0.52, 0.794, -1.331]}
        rotation={[0, 1.375, 0]}
        scale={0.383}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials['Material.017']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.鼠标.geometry}
        material={materials['Material.013']}
        position={[0.531, 0.828, -1.369]}
        rotation={[-Math.PI / 2, 0, -1.766]}
        scale={[-0.011, -0.002, -0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.墙上吸音板.geometry}
        material={materials['Material.011']}
        position={[-0.458, 1.918, -1.687]}
        rotation={[-2.132, 0.583, -2.29]}
        scale={[0.158, 0.253, 0.158]}
      />
      <group
        position={[0.056, 0.553, -0.861]}
        rotation={[0, -1.275, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_1.geometry}
          material={materials['Material.019']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_2.geometry}
          material={materials['Material.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GirlHair4002.geometry}
        material={materials['Material.048']}
        position={[-0.2, 1.638, -1.694]}
        rotation={[Math.PI / 2, 0, -1.671]}
        scale={[0.071, 0.05, 0.05]}
      />
      <group
        position={[-1.655, 0.349, -0.49]}
        rotation={[Math.PI / 2, 0, -1.362]}
        scale={[0.034, 0.005, 0.034]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_2.geometry}
          material={materials['Material.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_3.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_4.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group
        position={[-0.588, 0.937, -1.545]}
        rotation={[0, -1.106, 0]}
        scale={[0.032, 0.104, 0.104]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials['Material.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials['Material.020']}
        />
      </group>
      <group
        position={[-0.05, 0.789, -1.286]}
        rotation={[0, 0.066, 0]}
        scale={[0.146, 0.146, 0.069]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials['Material.006']}
        />
      </group>
      <group
        position={[-0.716, 1.693, -1.722]}
        rotation={[0, 0.368, 0]}
        scale={0.127}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube132.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube132_1.geometry}
          material={materials['Material.025']}
        />
      </group>
      <group
        position={[-1.555, 1.681, -1.053]}
        rotation={[0, 0.921, 0]}
        scale={0.127}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.025']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[-0.17, 1.533, -1.865]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-0.165, 1.535, -1.703]}
        scale={6.306}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.029']}
        position={[-1.426, 2.224, 0.748]}
        rotation={[0, -0.849, 0]}
        scale={[0.453, 0.021, 0.151]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder052.geometry}
        material={materials['Material.050']}
        position={[-1.327, 1.738, 1.077]}
        scale={[0.008, 0.716, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials['Material.030']}
        position={[-1.173, 1.352, 1.278]}
        scale={0.05}>
        <group position={[-0.034, -3.961, 0]} scale={1.376}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_1.geometry}
            material={materials['Material.031']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_2.geometry}
            material={materials['Material.033']}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.034']}
        position={[-1.173, 1.86, 1.284]}
        scale={[0.008, 0.526, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials['Material.030']}
        position={[-0.978, 1.533, 1.447]}
        scale={0.05}>
        <group position={[-0.034, -3.961, 0]} scale={1.376}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere004_1.geometry}
            material={materials['Material.031']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere004_2.geometry}
            material={materials['Material.033']}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.034']}
        position={[-0.978, 1.945, 1.452]}
        scale={[0.008, 0.402, 0.008]}
      />
      <group position={[-0.935, 0.919, -1.324]} scale={0.114}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.网格.geometry}
          material={materials.瓶身材质}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.网格_1.geometry}
          material={materials.瓶身图案}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.网格_2.geometry}
          material={materials.瓶盖材质}
        />
      </group>
      <group position={[-0.732, 0.961, -1.268]} scale={[0.009, 0.009, 0.014]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials['Material.041']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials['Material.042']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials['Material.052']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_3.geometry}
          material={materials['Material.053']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.地毯.geometry}
        material={materials['Material.008']}
        position={[1.757, 0.115, 0.323]}
        rotation={[0, 0.25, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={materials['Material.009']}
        position={[-1.327, 1.119, 1.071]}
        scale={0.05}>
        <group position={[-0.034, -3.961, 0]} scale={1.376}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere006_1.geometry}
            material={materials['Material.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere006_2.geometry}
            material={materials['Material.022']}
          />
        </group>
      </mesh>
      <group
        position={[-1.201, 0.302, 1.252]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[-0.128, -0.013, -0.128]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016.geometry}
          material={materials['Material.035']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_1.geometry}
          material={materials['Material.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder047.geometry}
          material={materials['Material.038']}
        />
      </group>
      <group
        position={[-1.844, 0.935, -0.063]}
        rotation={[1.68, 0, -1.385]}
        scale={4.679}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_1'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_2'].geometry}
          material={materials['SVGMat.019']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_3'].geometry}
          material={materials['SVGMat.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_4'].geometry}
          material={materials['SVGMat.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_5'].geometry}
          material={materials['SVGMat.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_6'].geometry}
          material={materials['SVGMat.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_7'].geometry}
          material={materials['SVGMat.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_8'].geometry}
          material={materials['SVGMat.026']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_9'].geometry}
          material={materials['SVGMat.027']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_10'].geometry}
          material={materials['SVGMat.028']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_11'].geometry}
          material={materials['SVGMat.029']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_12'].geometry}
          material={materials['SVGMat.030']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_13'].geometry}
          material={materials['SVGMat.031']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2_14'].geometry}
          material={materials['SVGMat.033']}
        />
      </group>
      <group scale={3.416}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_1'].geometry}
          material={materials['SVGMat.209']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_2'].geometry}
          material={materials['SVGMat.208']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_3'].geometry}
          material={materials['SVGMat.207']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_4'].geometry}
          material={materials['SVGMat.206']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_5'].geometry}
          material={materials['SVGMat.205']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_6'].geometry}
          material={materials['SVGMat.204']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_7'].geometry}
          material={materials['SVGMat.203']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_8'].geometry}
          material={materials['SVGMat.202']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_9'].geometry}
          material={materials['SVGMat.201']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_10'].geometry}
          material={materials['SVGMat.200']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_11'].geometry}
          material={materials['SVGMat.199']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_12'].geometry}
          material={materials['SVGMat.198']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_13'].geometry}
          material={materials['SVGMat.197']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['path881-2007_14'].geometry}
          material={materials['SVGMat.196']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.path1168.geometry}
        material={materials['Material.003']}
        position={[-1.553, 1.057, 0.953]}
        rotation={[1.685, 0, -2.052]}
        scale={3.583}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.竖屏.geometry}
        material={materials['computer black.002']}
        position={[-1.23, 1.062, -1.183]}
        rotation={[-Math.PI, 0.706, -Math.PI]}
        scale={0.23}>
        <group
          position={[0, 1.065, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.106, 1, 1.989]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials['computer black.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials['5 Light lamp blueLIGHT.002']}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials.Body}
        position={[1.128, 0.394, -1.071]}
        rotation={[0, -0.763, -Math.PI / 2]}
        scale={0.24}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ear_L.geometry}
          material={materials.Body}
          position={[-0.803, 0.404, 0.767]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ear_R.geometry}
          material={materials.Body}
          position={[-0.823, 0.424, -0.754]}
        />
        <group position={[-0.432, 1.015, 0.355]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere008.geometry}
            material={materials['Eye-White']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere008_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere008_2.geometry}
            material={materials['Material.023']}
          />
        </group>
        <group position={[-0.47, 0.981, -0.404]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere007.geometry}
            material={materials['Eye-White']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere007_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere007_2.geometry}
            material={materials['Material.023']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Foot_R.geometry}
          material={materials.SkinColor}
          position={[1.142, 0.516, -0.566]}
          rotation={[0.075, -0.002, -0.027]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Foot_R001.geometry}
          material={materials.SkinColor}
          position={[1.138, 0.459, 0.606]}
          rotation={[0.355, -0.038, -0.041]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hand_R.geometry}
          material={materials.SkinColor}
          position={[0.302, 0.273, -0.82]}
          rotation={[0.461, -0.315, 0.153]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hnad_L.geometry}
          material={materials.SkinColor}
          position={[0.374, 0.298, 0.932]}
        />
        <group position={[-0.136, 0.926, -0.012]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={materials.SkinColor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_1.geometry}
            material={materials.NoseTop}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tail.geometry}
          material={materials.SkinColor}
          position={[0.848, -0.876, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tooth.geometry}
          material={materials.Tooth}
          position={[0.009, 1.01, 0.013]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.原石容器.geometry}
        material={materials.原石柜子}
        position={[0.403, 0.102, 1.289]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.001']}
          position={[0, 0.919, 0]}
          scale={[0.972, 1.037, 0.972]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.原石柜子}
          position={[0, 1.778, 0]}
          scale={[0.896, 1.666, 0.896]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.原石.geometry}
          material={materials['Material.054']}
          position={[0.011, 0.989, -0.003]}
          rotation={[-0.791, 0.101, 1.672]}
          scale={[-1.013, -2.131, -1.013]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.原石001.geometry}
          material={materials['Material.054']}
          position={[0.011, 1.479, -0.003]}
          rotation={[-0.791, 0.101, 1.672]}
          scale={[-1.013, -2.131, -1.013]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.原石002.geometry}
          material={materials['Material.054']}
          position={[0.011, 0.494, -0.003]}
          rotation={[-0.791, 0.101, 1.672]}
          scale={[-1.013, -2.131, -1.013]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.桌子.geometry}
        material={nodes.桌子.material}
        position={[0, 0.112, 0]}
        rotation={[0, 0.068, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.洒水瓶.geometry}
        material={materials['Material.064']}
        position={[-1.366, 0.321, 0.471]}
        scale={1.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.喷嘴.geometry}
          material={nodes.喷嘴.material}
          position={[0, 0.071, 0]}
          scale={[0.12, 0.076, 0.08]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['研发组小屋-墙'].geometry}
        material={materials.材质}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.404, 0.196, 0.518]}
        scale={[0.793, 0.617, 0.793]}
      />
      <group
        position={[-1.825, 1.58, 0.278]}
        rotation={[1.794, -0.033, -1.756]}
        scale={[1.907, 1.499, 1.907]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002.geometry}
          material={materials['SVGMat.032']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_1.geometry}
          material={materials['SVGMat.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_2.geometry}
          material={materials['SVGMat.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_3.geometry}
          material={materials['SVGMat.038']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_4.geometry}
          material={materials['SVGMat.040']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_5.geometry}
          material={materials['SVGMat.041']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_6.geometry}
          material={materials['SVGMat.042']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_7.geometry}
          material={materials['SVGMat.043']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_8.geometry}
          material={materials['SVGMat.044']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_9.geometry}
          material={materials['SVGMat.045']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_10.geometry}
          material={materials['SVGMat.046']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ellipse284002_11.geometry}
          material={materials['SVGMat.047']}
        />
      </group>
      <group
        position={[-1.711, 1.121, 0.738]}
        rotation={[Math.PI / 2, 0, -1.8]}
        scale={3.658}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve005_1.geometry}
          material={materials['Material.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve005_2.geometry}
          material={materials['Material.067']}
        />
      </group>
      <group
        position={[-1.867, 1.328, -0.012]}
        rotation={[1.432, 0.006, -1.398]}
        scale={3.009}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_1.geometry}
          material={materials['SVGMat.069']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_2.geometry}
          material={materials['SVGMat.070']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_3.geometry}
          material={materials['SVGMat.072']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_4.geometry}
          material={materials['SVGMat.074']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_5.geometry}
          material={materials['SVGMat.075']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_6.geometry}
          material={materials['SVGMat.076']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_7.geometry}
          material={materials['SVGMat.077']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_8.geometry}
          material={materials['SVGMat.078']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path1847_9.geometry}
          material={materials['SVGMat.079']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/dev_interior.gltf')
