/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    [key: string]: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
}

export function ProductModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/product_interior.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder056.geometry}
        material={nodes.Cylinder056.material}
        position={[0.122, 0.49, 1.425]}
        rotation={[0, 0.371, 0]}
        scale={[0.062, 0.393, 0.058]}
      />
      <group
        position={[1.211, 0.123, 1.11]}
        rotation={[0, 1.18, 0]}
        scale={0.233}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_3.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_4.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_5.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_6.geometry}
          material={materials['Material.013']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['Material.020']}
        position={[-0.371, 0.489, 1.422]}
        rotation={[0, 0.371, 0]}
        scale={[0.984, 0.897, 0.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-0.841, 0.49, 1.58]}
        rotation={[0, 0.371, 0]}
        scale={[0.062, 0.393, 0.058]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[1.074, 0.49, 1.55]}
        rotation={[0, 0.052, 0]}
        scale={[0.063, 0.393, 0.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Material.020']}
        position={[0.607, 0.489, 1.408]}
        rotation={[0, 0.052, 0]}
        scale={[0.996, 0.897, 0.897]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[-0.571, 0.49, 0.723]}
        rotation={[0, 0.616, 0]}
        scale={[0.062, 0.393, 0.058]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials['Material.020']}
        position={[-1.049, 0.489, 0.84]}
        rotation={[0, 0.616, 0]}
        scale={[0.984, 0.897, 0.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[-1.467, 0.49, 1.108]}
        rotation={[0, 0.616, 0]}
        scale={[0.062, 0.393, 0.058]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[0.563, 0.49, 0.56]}
        rotation={[0, 0.297, 0]}
        scale={[0.063, 0.393, 0.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials['Material.020']}
        position={[0.002, 0.489, 0.559]}
        rotation={[0, 0.297, 0]}
        scale={[1.163, 0.897, 0.897]}
      />
      <group
        position={[1.212, 0.203, 0.552]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.725, 0.646, 0.662]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_1.geometry}
          material={materials['Material.019']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_2.geometry}
          material={materials['Material.020']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[1.849, 0.49, 0.549]}
        rotation={[0, 0.297, 0]}
        scale={[0.063, 0.393, 0.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials['Material.026']}
        position={[-0.024, 0.738, 0.09]}
        rotation={[0, 0.466, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={nodes.Circle006.material}
        position={[-1.241, 1.184, 1.426]}
        rotation={[Math.PI / 2, 0, -2.385]}
        scale={0.285}
      />
      <group
        position={[-0.585, 1.421, -1.306]}
        rotation={[-1.771, -0.058, -1.632]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material_0_1.geometry}
          material={materials['Material.015']}
        />
      </group>
      <group
        position={[-0.962, 1.526, -0.991]}
        rotation={[-1.376, 0.244, -1.515]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material_0002.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material_0002_1.geometry}
          material={materials['Material.016']}
        />
      </group>
      <group
        position={[-1.064, 1.994, -0.982]}
        rotation={[-2.304, 0.854, -0.654]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material_0003.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material_0003_1.geometry}
          material={materials['Material.017']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.盆栽.geometry}
        material={materials.plant}
        position={[0.622, 0.104, 1.665]}
        scale={0.133}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Leaf2}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle011.geometry}
        material={nodes.Circle011.material}
        position={[0.32, 1.148, -1.553]}
        rotation={[1.895, 0, 0]}
        scale={0.081}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[0.32, 1.169, -1.626]}
        scale={0.026}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[0.32, 1.149, -1.645]}
        rotation={[0.715, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.32, 0.989, -1.768]}
        rotation={[-0.012, 0, 0]}
        scale={0.026}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[0.32, 0.965, -1.762]}
        rotation={[-0.645, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={nodes.Cylinder020.material}
        position={[0.329, 0.753, -1.634]}
        scale={[0.146, 0.015, 0.146]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle012.geometry}
        material={materials['Material.001']}
        position={[1.692, 0.737, -0.317]}
        scale={0.109}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle013.geometry}
        material={materials['Material.001']}
        position={[1.597, 0.836, -0.588]}
        scale={0.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['研发组小屋-墙'].geometry}
        material={nodes['研发组小屋-墙'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.抓球机.geometry}
        material={materials['Material.022']}
        position={[0.217, 0.372, -0.244]}
        rotation={[0, -1.353, 0]}
        scale={[0.55, 0.29, 0.387]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[0, 3.032, 0.381]}
          scale={[1, 0.823, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.022']}
          position={[0, 6.759, 0.381]}
          scale={[0.972, 1.842, 1.38]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials['Material.022']}
            position={[0, -0.282, 0]}
            scale={[1, 1.127, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials['Material.022']}
              position={[0, -0.233, 0]}
              scale={[1, 0.887, 1]}
            />
          </mesh>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials['Material.026']}
          position={[-0.016, 2.031, -0.643]}
          rotation={[2.051, 1.131, 3.015]}
          scale={[3.141, 2.799, 2.034]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={materials['Material.001']}
          position={[0, 4.867, 0.381]}
          rotation={[0, 1.339, 0]}
          scale={[2.551, 3.445, 1.861]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere001.geometry}
            material={materials['Material.018']}
            position={[0.056, -0.389, 0.01]}
            rotation={[1.023, 0.646, 1.203]}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-1.303, 0.486, -0.662]}
        rotation={[0, -0.347, 0]}
        scale={[0.164, 0.378, 0.164]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-1.095, 0.348, -1.07]}
        rotation={[0, -0.412, 0]}
        scale={[0.112, 0.258, 0.112]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials['Material.001']}
        position={[-1.1, 2.032, -0.954]}
        rotation={[0, -1.145, 0]}
        scale={[0.874, 0.426, 0.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials['Material.024']}
        position={[-1.753, 0.504, 0.531]}
        rotation={[-0.486, 0.202, -1.426]}
        scale={0.177}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Mirror}
        position={[-1.651, 1.587, 0.879]}
        rotation={[0, 0.471, 0]}
        scale={[0.044, 0.423, 0.325]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.阀.geometry}
        material={nodes.阀.material}
        position={[-1.303, 0.912, -0.662]}
        scale={[0.032, 0.09, 0.032]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014.geometry}
          material={nodes.Cylinder014.material}
          position={[-2.708, 0.875, -1.989]}
          rotation={[-1.584, 0.004, -2.167]}
          scale={[0.902, 3.264, 0.323]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={nodes.Cylinder015.material}
          position={[0.044, 0.875, -3.29]}
          rotation={[-1.569, 0.013, -3.137]}
          scale={[0.902, 3.264, 0.323]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus.geometry}
          material={nodes.Torus.material}
          position={[-0.041, 0.874, 0.028]}
          scale={[4.301, 1.54, 4.301]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.阀001.geometry}
        material={nodes.阀001.material}
        position={[-1.095, 0.635, -1.07]}
        scale={[0.022, 0.062, 0.022]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={nodes.Cylinder013.material}
          position={[-2.708, 0.875, -1.989]}
          rotation={[-1.584, 0.004, -2.167]}
          scale={[0.902, 3.264, 0.323]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016.geometry}
          material={nodes.Cylinder016.material}
          position={[0.044, 0.875, -3.29]}
          rotation={[-1.569, 0.013, -3.137]}
          scale={[0.902, 3.264, 0.323]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus002.geometry}
          material={nodes.Torus002.material}
          position={[-0.041, 0.874, 0.028]}
          scale={[4.301, 1.54, 4.301]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials['Material.021']}
        position={[-1.485, 0.304, 0.479]}
        rotation={[-2.889, 1.068, -0.313]}
        scale={[0.352, 0.172, 0.352]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={materials['Material.024']}
        position={[-1.843, 0.501, 0.149]}
        rotation={[-0.479, 0.111, -1.474]}
        scale={0.177}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials['Material.021']}
        position={[-1.572, 0.304, 0.131]}
        rotation={[-2.83, 1.167, -0.378]}
        scale={[0.352, 0.172, 0.352]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle009.geometry}
        material={materials['Material.024']}
        position={[-1.818, 0.49, -0.253]}
        rotation={[-0.482, -0.154, -1.611]}
        scale={0.177}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials['Material.021']}
        position={[-1.554, 0.293, -0.19]}
        rotation={[-2.199, 1.422, -1.028]}
        scale={[0.352, 0.172, 0.352]}
      />
    </group>
  )
}

useGLTF.preload('/product_interior.glb')
